title: "SIVA KUMAR's Resume"
description: "A complete rundown of my educational and professional journey till date."

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: [Your Google Analytics tracking ID]

# Menu links
menu:
  - title: "Home"
    url: "/"
  - title: "Experience"
    url: "/experience"

# Social links
twitter_username: sivakumar36688 # DO NOT include the @ before your name
github_username:  AmbitiousSam
linkedin_username: sivakumark1
email: sk800489@gmai.com
phone: +91 9490647560

show_downloads: true # whether to show download links
